// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/usecase.go -destination=internal/usecase/mock/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	input "github.com/phamquanandpad/training-project/go/services/todo/internal/usecase/input"
	output "github.com/phamquanandpad/training-project/go/services/todo/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoGetter is a mock of TodoGetter interface.
type MockTodoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTodoGetterMockRecorder
	isgomock struct{}
}

// MockTodoGetterMockRecorder is the mock recorder for MockTodoGetter.
type MockTodoGetterMockRecorder struct {
	mock *MockTodoGetter
}

// NewMockTodoGetter creates a new mock instance.
func NewMockTodoGetter(ctrl *gomock.Controller) *MockTodoGetter {
	mock := &MockTodoGetter{ctrl: ctrl}
	mock.recorder = &MockTodoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoGetter) EXPECT() *MockTodoGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTodoGetter) Get(ctx context.Context, in *input.TodoGetter) (*output.TodoGetter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, in)
	ret0, _ := ret[0].(*output.TodoGetter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTodoGetterMockRecorder) Get(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTodoGetter)(nil).Get), ctx, in)
}

// MockTodoLister is a mock of TodoLister interface.
type MockTodoLister struct {
	ctrl     *gomock.Controller
	recorder *MockTodoListerMockRecorder
	isgomock struct{}
}

// MockTodoListerMockRecorder is the mock recorder for MockTodoLister.
type MockTodoListerMockRecorder struct {
	mock *MockTodoLister
}

// NewMockTodoLister creates a new mock instance.
func NewMockTodoLister(ctrl *gomock.Controller) *MockTodoLister {
	mock := &MockTodoLister{ctrl: ctrl}
	mock.recorder = &MockTodoListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoLister) EXPECT() *MockTodoListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockTodoLister) List(ctx context.Context, in *input.TodoLister) (*output.TodoLister, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, in)
	ret0, _ := ret[0].(*output.TodoLister)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTodoListerMockRecorder) List(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTodoLister)(nil).List), ctx, in)
}

// MockTodoCreator is a mock of TodoCreator interface.
type MockTodoCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCreatorMockRecorder
	isgomock struct{}
}

// MockTodoCreatorMockRecorder is the mock recorder for MockTodoCreator.
type MockTodoCreatorMockRecorder struct {
	mock *MockTodoCreator
}

// NewMockTodoCreator creates a new mock instance.
func NewMockTodoCreator(ctrl *gomock.Controller) *MockTodoCreator {
	mock := &MockTodoCreator{ctrl: ctrl}
	mock.recorder = &MockTodoCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCreator) EXPECT() *MockTodoCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoCreator) Create(ctx context.Context, in *input.TodoCreator) (*output.TodoCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*output.TodoCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTodoCreatorMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoCreator)(nil).Create), ctx, in)
}

// MockTodoUpdater is a mock of TodoUpdater interface.
type MockTodoUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockTodoUpdaterMockRecorder
	isgomock struct{}
}

// MockTodoUpdaterMockRecorder is the mock recorder for MockTodoUpdater.
type MockTodoUpdaterMockRecorder struct {
	mock *MockTodoUpdater
}

// NewMockTodoUpdater creates a new mock instance.
func NewMockTodoUpdater(ctrl *gomock.Controller) *MockTodoUpdater {
	mock := &MockTodoUpdater{ctrl: ctrl}
	mock.recorder = &MockTodoUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoUpdater) EXPECT() *MockTodoUpdaterMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockTodoUpdater) Update(ctx context.Context, in *input.TodoUpdater) (*output.TodoUpdater, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, in)
	ret0, _ := ret[0].(*output.TodoUpdater)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTodoUpdaterMockRecorder) Update(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoUpdater)(nil).Update), ctx, in)
}

// MockTodoDeleter is a mock of TodoDeleter interface.
type MockTodoDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockTodoDeleterMockRecorder
	isgomock struct{}
}

// MockTodoDeleterMockRecorder is the mock recorder for MockTodoDeleter.
type MockTodoDeleterMockRecorder struct {
	mock *MockTodoDeleter
}

// NewMockTodoDeleter creates a new mock instance.
func NewMockTodoDeleter(ctrl *gomock.Controller) *MockTodoDeleter {
	mock := &MockTodoDeleter{ctrl: ctrl}
	mock.recorder = &MockTodoDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoDeleter) EXPECT() *MockTodoDeleterMockRecorder {
	return m.recorder
}

// SoftDelete mocks base method.
func (m *MockTodoDeleter) SoftDelete(ctx context.Context, in *input.TodoDeleter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockTodoDeleterMockRecorder) SoftDelete(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockTodoDeleter)(nil).SoftDelete), ctx, in)
}

// MockUserGetter is a mock of UserGetter interface.
type MockUserGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUserGetterMockRecorder
	isgomock struct{}
}

// MockUserGetterMockRecorder is the mock recorder for MockUserGetter.
type MockUserGetterMockRecorder struct {
	mock *MockUserGetter
}

// NewMockUserGetter creates a new mock instance.
func NewMockUserGetter(ctrl *gomock.Controller) *MockUserGetter {
	mock := &MockUserGetter{ctrl: ctrl}
	mock.recorder = &MockUserGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserGetter) EXPECT() *MockUserGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockUserGetter) Get(ctx context.Context, in *input.UserGetter) (*output.UserGetter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, in)
	ret0, _ := ret[0].(*output.UserGetter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUserGetterMockRecorder) Get(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUserGetter)(nil).Get), ctx, in)
}

// MockUserCreator is a mock of UserCreator interface.
type MockUserCreator struct {
	ctrl     *gomock.Controller
	recorder *MockUserCreatorMockRecorder
	isgomock struct{}
}

// MockUserCreatorMockRecorder is the mock recorder for MockUserCreator.
type MockUserCreatorMockRecorder struct {
	mock *MockUserCreator
}

// NewMockUserCreator creates a new mock instance.
func NewMockUserCreator(ctrl *gomock.Controller) *MockUserCreator {
	mock := &MockUserCreator{ctrl: ctrl}
	mock.recorder = &MockUserCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCreator) EXPECT() *MockUserCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserCreator) Create(ctx context.Context, in *input.UserCreator) (*output.UserCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, in)
	ret0, _ := ret[0].(*output.UserCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserCreatorMockRecorder) Create(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserCreator)(nil).Create), ctx, in)
}

// MockDataValidator is a mock of DataValidator interface.
type MockDataValidator struct {
	ctrl     *gomock.Controller
	recorder *MockDataValidatorMockRecorder
	isgomock struct{}
}

// MockDataValidatorMockRecorder is the mock recorder for MockDataValidator.
type MockDataValidatorMockRecorder struct {
	mock *MockDataValidator
}

// NewMockDataValidator creates a new mock instance.
func NewMockDataValidator(ctrl *gomock.Controller) *MockDataValidator {
	mock := &MockDataValidator{ctrl: ctrl}
	mock.recorder = &MockDataValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataValidator) EXPECT() *MockDataValidatorMockRecorder {
	return m.recorder
}

// ValidateUserRequest mocks base method.
func (m *MockDataValidator) ValidateUserRequest(ctx context.Context, in *input.UserRequestValidator) (*output.UserRequestValidator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserRequest", ctx, in)
	ret0, _ := ret[0].(*output.UserRequestValidator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateUserRequest indicates an expected call of ValidateUserRequest.
func (mr *MockDataValidatorMockRecorder) ValidateUserRequest(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserRequest", reflect.TypeOf((*MockDataValidator)(nil).ValidateUserRequest), ctx, in)
}
