// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/usecase.go -destination=internal/usecase/mock/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	input "github.com/phamquanandpad/training-project/go/services/todo-bff/internal/usecase/input"
	output "github.com/phamquanandpad/training-project/go/services/todo-bff/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLogin is a mock of UserLogin interface.
type MockUserLogin struct {
	ctrl     *gomock.Controller
	recorder *MockUserLoginMockRecorder
	isgomock struct{}
}

// MockUserLoginMockRecorder is the mock recorder for MockUserLogin.
type MockUserLoginMockRecorder struct {
	mock *MockUserLogin
}

// NewMockUserLogin creates a new mock instance.
func NewMockUserLogin(ctrl *gomock.Controller) *MockUserLogin {
	mock := &MockUserLogin{ctrl: ctrl}
	mock.recorder = &MockUserLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLogin) EXPECT() *MockUserLoginMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockUserLogin) Login(ctx context.Context, in *input.UserLogin) (*output.UserLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, in)
	ret0, _ := ret[0].(*output.UserLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserLoginMockRecorder) Login(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserLogin)(nil).Login), ctx, in)
}

// MockUserRegister is a mock of UserRegister interface.
type MockUserRegister struct {
	ctrl     *gomock.Controller
	recorder *MockUserRegisterMockRecorder
	isgomock struct{}
}

// MockUserRegisterMockRecorder is the mock recorder for MockUserRegister.
type MockUserRegisterMockRecorder struct {
	mock *MockUserRegister
}

// NewMockUserRegister creates a new mock instance.
func NewMockUserRegister(ctrl *gomock.Controller) *MockUserRegister {
	mock := &MockUserRegister{ctrl: ctrl}
	mock.recorder = &MockUserRegisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRegister) EXPECT() *MockUserRegisterMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockUserRegister) Register(ctx context.Context, in *input.UserRegister) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockUserRegisterMockRecorder) Register(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRegister)(nil).Register), ctx, in)
}

// MockTokenRefresh is a mock of TokenRefresh interface.
type MockTokenRefresh struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRefreshMockRecorder
	isgomock struct{}
}

// MockTokenRefreshMockRecorder is the mock recorder for MockTokenRefresh.
type MockTokenRefreshMockRecorder struct {
	mock *MockTokenRefresh
}

// NewMockTokenRefresh creates a new mock instance.
func NewMockTokenRefresh(ctrl *gomock.Controller) *MockTokenRefresh {
	mock := &MockTokenRefresh{ctrl: ctrl}
	mock.recorder = &MockTokenRefreshMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRefresh) EXPECT() *MockTokenRefreshMockRecorder {
	return m.recorder
}

// RefreshToken mocks base method.
func (m *MockTokenRefresh) RefreshToken(ctx context.Context, in *input.TokenRefresh) (*output.TokenRefresh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, in)
	ret0, _ := ret[0].(*output.TokenRefresh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockTokenRefreshMockRecorder) RefreshToken(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockTokenRefresh)(nil).RefreshToken), ctx, in)
}

// MockTokenVerify is a mock of TokenVerify interface.
type MockTokenVerify struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVerifyMockRecorder
	isgomock struct{}
}

// MockTokenVerifyMockRecorder is the mock recorder for MockTokenVerify.
type MockTokenVerifyMockRecorder struct {
	mock *MockTokenVerify
}

// NewMockTokenVerify creates a new mock instance.
func NewMockTokenVerify(ctrl *gomock.Controller) *MockTokenVerify {
	mock := &MockTokenVerify{ctrl: ctrl}
	mock.recorder = &MockTokenVerifyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVerify) EXPECT() *MockTokenVerifyMockRecorder {
	return m.recorder
}

// VerifyToken mocks base method.
func (m *MockTokenVerify) VerifyToken(ctx context.Context, in *input.TokenVerify) (*output.TokenVerify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, in)
	ret0, _ := ret[0].(*output.TokenVerify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenVerifyMockRecorder) VerifyToken(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokenVerify)(nil).VerifyToken), ctx, in)
}

// MockTodoGetter is a mock of TodoGetter interface.
type MockTodoGetter struct {
	ctrl     *gomock.Controller
	recorder *MockTodoGetterMockRecorder
	isgomock struct{}
}

// MockTodoGetterMockRecorder is the mock recorder for MockTodoGetter.
type MockTodoGetterMockRecorder struct {
	mock *MockTodoGetter
}

// NewMockTodoGetter creates a new mock instance.
func NewMockTodoGetter(ctrl *gomock.Controller) *MockTodoGetter {
	mock := &MockTodoGetter{ctrl: ctrl}
	mock.recorder = &MockTodoGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoGetter) EXPECT() *MockTodoGetterMockRecorder {
	return m.recorder
}

// GetTodo mocks base method.
func (m *MockTodoGetter) GetTodo(ctx context.Context, in *input.TodoGetter) (*output.TodoGetter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo", ctx, in)
	ret0, _ := ret[0].(*output.TodoGetter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoGetterMockRecorder) GetTodo(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoGetter)(nil).GetTodo), ctx, in)
}

// MockTodoLister is a mock of TodoLister interface.
type MockTodoLister struct {
	ctrl     *gomock.Controller
	recorder *MockTodoListerMockRecorder
	isgomock struct{}
}

// MockTodoListerMockRecorder is the mock recorder for MockTodoLister.
type MockTodoListerMockRecorder struct {
	mock *MockTodoLister
}

// NewMockTodoLister creates a new mock instance.
func NewMockTodoLister(ctrl *gomock.Controller) *MockTodoLister {
	mock := &MockTodoLister{ctrl: ctrl}
	mock.recorder = &MockTodoListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoLister) EXPECT() *MockTodoListerMockRecorder {
	return m.recorder
}

// ListTodos mocks base method.
func (m *MockTodoLister) ListTodos(ctx context.Context, in *input.TodoLister) (*output.TodoLister, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodos", ctx, in)
	ret0, _ := ret[0].(*output.TodoLister)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodos indicates an expected call of ListTodos.
func (mr *MockTodoListerMockRecorder) ListTodos(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodos", reflect.TypeOf((*MockTodoLister)(nil).ListTodos), ctx, in)
}

// MockTodoCreator is a mock of TodoCreator interface.
type MockTodoCreator struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCreatorMockRecorder
	isgomock struct{}
}

// MockTodoCreatorMockRecorder is the mock recorder for MockTodoCreator.
type MockTodoCreatorMockRecorder struct {
	mock *MockTodoCreator
}

// NewMockTodoCreator creates a new mock instance.
func NewMockTodoCreator(ctrl *gomock.Controller) *MockTodoCreator {
	mock := &MockTodoCreator{ctrl: ctrl}
	mock.recorder = &MockTodoCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCreator) EXPECT() *MockTodoCreatorMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoCreator) CreateTodo(ctx context.Context, in *input.TodoCreator) (*output.TodoCreator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, in)
	ret0, _ := ret[0].(*output.TodoCreator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoCreatorMockRecorder) CreateTodo(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoCreator)(nil).CreateTodo), ctx, in)
}

// MockTodoUpdater is a mock of TodoUpdater interface.
type MockTodoUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockTodoUpdaterMockRecorder
	isgomock struct{}
}

// MockTodoUpdaterMockRecorder is the mock recorder for MockTodoUpdater.
type MockTodoUpdaterMockRecorder struct {
	mock *MockTodoUpdater
}

// NewMockTodoUpdater creates a new mock instance.
func NewMockTodoUpdater(ctrl *gomock.Controller) *MockTodoUpdater {
	mock := &MockTodoUpdater{ctrl: ctrl}
	mock.recorder = &MockTodoUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoUpdater) EXPECT() *MockTodoUpdaterMockRecorder {
	return m.recorder
}

// UpdateTodo mocks base method.
func (m *MockTodoUpdater) UpdateTodo(ctx context.Context, in *input.TodoUpdater) (*output.TodoUpdater, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, in)
	ret0, _ := ret[0].(*output.TodoUpdater)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoUpdaterMockRecorder) UpdateTodo(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoUpdater)(nil).UpdateTodo), ctx, in)
}

// MockTodoDeleter is a mock of TodoDeleter interface.
type MockTodoDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockTodoDeleterMockRecorder
	isgomock struct{}
}

// MockTodoDeleterMockRecorder is the mock recorder for MockTodoDeleter.
type MockTodoDeleterMockRecorder struct {
	mock *MockTodoDeleter
}

// NewMockTodoDeleter creates a new mock instance.
func NewMockTodoDeleter(ctrl *gomock.Controller) *MockTodoDeleter {
	mock := &MockTodoDeleter{ctrl: ctrl}
	mock.recorder = &MockTodoDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoDeleter) EXPECT() *MockTodoDeleterMockRecorder {
	return m.recorder
}

// DeleteTodo mocks base method.
func (m *MockTodoDeleter) DeleteTodo(ctx context.Context, in *input.TodoDeleter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoDeleterMockRecorder) DeleteTodo(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoDeleter)(nil).DeleteTodo), ctx, in)
}
