// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"context"
	"github.com/go-playground/validator/v10"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/config"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/domain/service"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/handler"
	auth2 "github.com/phamquanandpad/training-project/go/services/todo-bff/internal/handler/auth"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/infrastructure/auth"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/infrastructure/todo"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/middleware"
	"net/http"
)

// Injectors from wire.go:

func InitHttpServer(ctx context.Context, c *config.Config, v *validator.Validate) (http.Handler, func(), error) {
	middlewareMiddleware := middleware.NewMiddleware(c)
	todoConnection, cleanup, err := todo.NewTodoServiceConnection(c)
	if err != nil {
		return nil, nil, err
	}
	todoServiceClient := todo.NewTodoServiceClient(todoConnection)
	todoQueriesGateway := todo.NewTodoReader(todoServiceClient)
	todoGetter := service.NewTodoGetter(todoQueriesGateway)
	todoLister := service.NewTodoLister(todoQueriesGateway)
	todoCommandsGateway := todo.NewTodoWriter(todoServiceClient)
	todoCreator := service.NewTodoCreator(todoCommandsGateway)
	todoUpdater := service.NewTodoUpdater(todoCommandsGateway)
	todoDeleter := service.NewTodoDeleter(todoCommandsGateway)
	authTodoConnection, cleanup2, err := auth.NewAuthServiceConnection(c)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	authServiceClient := auth.NewAuthServiceClient(authTodoConnection)
	authReaderGateway := auth.NewAuthReader(authServiceClient)
	userLogin := service.NewUserLogin(authReaderGateway)
	userRegister := service.NewUserRegister(authReaderGateway)
	tokenRefresh := service.NewTokenRefresh(authReaderGateway)
	tokenVerify := service.NewTokenVerify(authReaderGateway)
	authenticator := auth2.NewAuthentication(ctx, tokenRefresh)
	httpHandler := handler.NewHTTPServer(c, v, middlewareMiddleware, todoGetter, todoLister, todoCreator, todoUpdater, todoDeleter, userLogin, userRegister, tokenRefresh, tokenVerify, authenticator)
	return httpHandler, func() {
		cleanup2()
		cleanup()
	}, nil
}
