// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/gateway.go -destination=internal/domain/gateway/mock/gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	todo "github.com/phamquanandpad/training-project/go/services/todo/internal/domain/model/todo"
	gomock "go.uber.org/mock/gomock"
)

// MockBinder is a mock of Binder interface.
type MockBinder struct {
	ctrl     *gomock.Controller
	recorder *MockBinderMockRecorder
	isgomock struct{}
}

// MockBinderMockRecorder is the mock recorder for MockBinder.
type MockBinderMockRecorder struct {
	mock *MockBinder
}

// NewMockBinder creates a new mock instance.
func NewMockBinder(ctrl *gomock.Controller) *MockBinder {
	mock := &MockBinder{ctrl: ctrl}
	mock.recorder = &MockBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinder) EXPECT() *MockBinderMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockBinder) Bind(arg0 context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", arg0)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockBinderMockRecorder) Bind(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockBinder)(nil).Bind), arg0)
}

// MockTodoQueriesGateway is a mock of TodoQueriesGateway interface.
type MockTodoQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockTodoQueriesGatewayMockRecorder is the mock recorder for MockTodoQueriesGateway.
type MockTodoQueriesGatewayMockRecorder struct {
	mock *MockTodoQueriesGateway
}

// NewMockTodoQueriesGateway creates a new mock instance.
func NewMockTodoQueriesGateway(ctrl *gomock.Controller) *MockTodoQueriesGateway {
	mock := &MockTodoQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockTodoQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoQueriesGateway) EXPECT() *MockTodoQueriesGatewayMockRecorder {
	return m.recorder
}

// GetTodo mocks base method.
func (m *MockTodoQueriesGateway) GetTodo(ctx context.Context, todoID todo.TodoID, userID todo.UserID) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo", ctx, todoID, userID)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoQueriesGatewayMockRecorder) GetTodo(ctx, todoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoQueriesGateway)(nil).GetTodo), ctx, todoID, userID)
}

// ListTodos mocks base method.
func (m *MockTodoQueriesGateway) ListTodos(ctx context.Context, userID todo.UserID, limit, offset int) ([]*todo.Todo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodos", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*todo.Todo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTodos indicates an expected call of ListTodos.
func (mr *MockTodoQueriesGatewayMockRecorder) ListTodos(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodos", reflect.TypeOf((*MockTodoQueriesGateway)(nil).ListTodos), ctx, userID, limit, offset)
}

// MockTodoCommandsGateway is a mock of TodoCommandsGateway interface.
type MockTodoCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockTodoCommandsGatewayMockRecorder is the mock recorder for MockTodoCommandsGateway.
type MockTodoCommandsGatewayMockRecorder struct {
	mock *MockTodoCommandsGateway
}

// NewMockTodoCommandsGateway creates a new mock instance.
func NewMockTodoCommandsGateway(ctrl *gomock.Controller) *MockTodoCommandsGateway {
	mock := &MockTodoCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockTodoCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCommandsGateway) EXPECT() *MockTodoCommandsGatewayMockRecorder {
	return m.recorder
}

// CreateTodo mocks base method.
func (m *MockTodoCommandsGateway) CreateTodo(ctx context.Context, newTodo todo.NewTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTodo", ctx, newTodo)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTodo indicates an expected call of CreateTodo.
func (mr *MockTodoCommandsGatewayMockRecorder) CreateTodo(ctx, newTodo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTodo", reflect.TypeOf((*MockTodoCommandsGateway)(nil).CreateTodo), ctx, newTodo)
}

// SoftDeleteTodo mocks base method.
func (m *MockTodoCommandsGateway) SoftDeleteTodo(ctx context.Context, todoID todo.TodoID, userID todo.UserID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteTodo", ctx, todoID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteTodo indicates an expected call of SoftDeleteTodo.
func (mr *MockTodoCommandsGatewayMockRecorder) SoftDeleteTodo(ctx, todoID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteTodo", reflect.TypeOf((*MockTodoCommandsGateway)(nil).SoftDeleteTodo), ctx, todoID, userID)
}

// UpdateTodo mocks base method.
func (m *MockTodoCommandsGateway) UpdateTodo(ctx context.Context, todoID todo.TodoID, userID todo.UserID, updateTodo todo.UpdateTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTodo", ctx, todoID, userID, updateTodo)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTodo indicates an expected call of UpdateTodo.
func (mr *MockTodoCommandsGatewayMockRecorder) UpdateTodo(ctx, todoID, userID, updateTodo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTodo", reflect.TypeOf((*MockTodoCommandsGateway)(nil).UpdateTodo), ctx, todoID, userID, updateTodo)
}

// MockUserQueriesGateway is a mock of UserQueriesGateway interface.
type MockUserQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockUserQueriesGatewayMockRecorder is the mock recorder for MockUserQueriesGateway.
type MockUserQueriesGatewayMockRecorder struct {
	mock *MockUserQueriesGateway
}

// NewMockUserQueriesGateway creates a new mock instance.
func NewMockUserQueriesGateway(ctrl *gomock.Controller) *MockUserQueriesGateway {
	mock := &MockUserQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockUserQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueriesGateway) EXPECT() *MockUserQueriesGatewayMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserQueriesGateway) GetUser(ctx context.Context, userID todo.UserID) (*todo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*todo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserQueriesGatewayMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserQueriesGateway)(nil).GetUser), ctx, userID)
}

// MockUserCommandsGateway is a mock of UserCommandsGateway interface.
type MockUserCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockUserCommandsGatewayMockRecorder is the mock recorder for MockUserCommandsGateway.
type MockUserCommandsGatewayMockRecorder struct {
	mock *MockUserCommandsGateway
}

// NewMockUserCommandsGateway creates a new mock instance.
func NewMockUserCommandsGateway(ctrl *gomock.Controller) *MockUserCommandsGateway {
	mock := &MockUserCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockUserCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCommandsGateway) EXPECT() *MockUserCommandsGatewayMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserCommandsGateway) CreateUser(ctx context.Context, newUser todo.NewUser) (*todo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, newUser)
	ret0, _ := ret[0].(*todo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserCommandsGatewayMockRecorder) CreateUser(ctx, newUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserCommandsGateway)(nil).CreateUser), ctx, newUser)
}
