// Code generated by MockGen. DO NOT EDIT.
// Source: internal/usecase/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/usecase/usecase.go -destination=internal/usecase/mock/usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	input "github.com/phamquanandpad/training-project/go/services/auth/internal/usecase/input"
	output "github.com/phamquanandpad/training-project/go/services/auth/internal/usecase/output"
	gomock "go.uber.org/mock/gomock"
)

// MockUserLogin is a mock of UserLogin interface.
type MockUserLogin struct {
	ctrl     *gomock.Controller
	recorder *MockUserLoginMockRecorder
	isgomock struct{}
}

// MockUserLoginMockRecorder is the mock recorder for MockUserLogin.
type MockUserLoginMockRecorder struct {
	mock *MockUserLogin
}

// NewMockUserLogin creates a new mock instance.
func NewMockUserLogin(ctrl *gomock.Controller) *MockUserLogin {
	mock := &MockUserLogin{ctrl: ctrl}
	mock.recorder = &MockUserLoginMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLogin) EXPECT() *MockUserLoginMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockUserLogin) Login(ctx context.Context, in *input.UserLogin) (*output.UserLogin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, in)
	ret0, _ := ret[0].(*output.UserLogin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserLoginMockRecorder) Login(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserLogin)(nil).Login), ctx, in)
}

// MockUserRegister is a mock of UserRegister interface.
type MockUserRegister struct {
	ctrl     *gomock.Controller
	recorder *MockUserRegisterMockRecorder
	isgomock struct{}
}

// MockUserRegisterMockRecorder is the mock recorder for MockUserRegister.
type MockUserRegisterMockRecorder struct {
	mock *MockUserRegister
}

// NewMockUserRegister creates a new mock instance.
func NewMockUserRegister(ctrl *gomock.Controller) *MockUserRegister {
	mock := &MockUserRegister{ctrl: ctrl}
	mock.recorder = &MockUserRegisterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRegister) EXPECT() *MockUserRegisterMockRecorder {
	return m.recorder
}

// Register mocks base method.
func (m *MockUserRegister) Register(ctx context.Context, in *input.UserRegister) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockUserRegisterMockRecorder) Register(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockUserRegister)(nil).Register), ctx, in)
}

// MockTokenRefresh is a mock of TokenRefresh interface.
type MockTokenRefresh struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRefreshMockRecorder
	isgomock struct{}
}

// MockTokenRefreshMockRecorder is the mock recorder for MockTokenRefresh.
type MockTokenRefreshMockRecorder struct {
	mock *MockTokenRefresh
}

// NewMockTokenRefresh creates a new mock instance.
func NewMockTokenRefresh(ctrl *gomock.Controller) *MockTokenRefresh {
	mock := &MockTokenRefresh{ctrl: ctrl}
	mock.recorder = &MockTokenRefreshMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRefresh) EXPECT() *MockTokenRefreshMockRecorder {
	return m.recorder
}

// RefreshToken mocks base method.
func (m *MockTokenRefresh) RefreshToken(ctx context.Context, in *input.TokenRefresh) (*output.TokenRefresh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, in)
	ret0, _ := ret[0].(*output.TokenRefresh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockTokenRefreshMockRecorder) RefreshToken(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockTokenRefresh)(nil).RefreshToken), ctx, in)
}

// MockTokenVerify is a mock of TokenVerify interface.
type MockTokenVerify struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVerifyMockRecorder
	isgomock struct{}
}

// MockTokenVerifyMockRecorder is the mock recorder for MockTokenVerify.
type MockTokenVerifyMockRecorder struct {
	mock *MockTokenVerify
}

// NewMockTokenVerify creates a new mock instance.
func NewMockTokenVerify(ctrl *gomock.Controller) *MockTokenVerify {
	mock := &MockTokenVerify{ctrl: ctrl}
	mock.recorder = &MockTokenVerifyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVerify) EXPECT() *MockTokenVerifyMockRecorder {
	return m.recorder
}

// VerifyToken mocks base method.
func (m *MockTokenVerify) VerifyToken(ctx context.Context, in *input.TokenVerify) (*output.TokenVerify, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, in)
	ret0, _ := ret[0].(*output.TokenVerify)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockTokenVerifyMockRecorder) VerifyToken(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockTokenVerify)(nil).VerifyToken), ctx, in)
}
