// Code generated by MockGen. DO NOT EDIT.
// Source: todo/todo/v1/todo_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=todo/todo/v1/todo_grpc.pb.go -destination=todo/todo/v1/mock/mock_todo_grpc.pb.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1 "github.com/phamquanandpad/training-project/grpc/go/todo/todo/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockTodoServiceClient is a mock of TodoServiceClient interface.
type MockTodoServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockTodoServiceClientMockRecorder
	isgomock struct{}
}

// MockTodoServiceClientMockRecorder is the mock recorder for MockTodoServiceClient.
type MockTodoServiceClientMockRecorder struct {
	mock *MockTodoServiceClient
}

// NewMockTodoServiceClient creates a new mock instance.
func NewMockTodoServiceClient(ctrl *gomock.Controller) *MockTodoServiceClient {
	mock := &MockTodoServiceClient{ctrl: ctrl}
	mock.recorder = &MockTodoServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoServiceClient) EXPECT() *MockTodoServiceClientMockRecorder {
	return m.recorder
}

// DeleteTodo mocks base method.
func (m *MockTodoServiceClient) DeleteTodo(ctx context.Context, in *v1.DeleteTodoRequest, opts ...grpc.CallOption) (*v1.DeleteTodoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteTodo", varargs...)
	ret0, _ := ret[0].(*v1.DeleteTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoServiceClientMockRecorder) DeleteTodo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoServiceClient)(nil).DeleteTodo), varargs...)
}

// GetTodo mocks base method.
func (m *MockTodoServiceClient) GetTodo(ctx context.Context, in *v1.GetTodoRequest, opts ...grpc.CallOption) (*v1.GetTodoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetTodo", varargs...)
	ret0, _ := ret[0].(*v1.GetTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoServiceClientMockRecorder) GetTodo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoServiceClient)(nil).GetTodo), varargs...)
}

// GetUser mocks base method.
func (m *MockTodoServiceClient) GetUser(ctx context.Context, in *v1.GetUserRequest, opts ...grpc.CallOption) (*v1.GetUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetUser", varargs...)
	ret0, _ := ret[0].(*v1.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTodoServiceClientMockRecorder) GetUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockTodoServiceClient)(nil).GetUser), varargs...)
}

// ListTodos mocks base method.
func (m *MockTodoServiceClient) ListTodos(ctx context.Context, in *v1.ListTodosRequest, opts ...grpc.CallOption) (*v1.ListTodosResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTodos", varargs...)
	ret0, _ := ret[0].(*v1.ListTodosResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodos indicates an expected call of ListTodos.
func (mr *MockTodoServiceClientMockRecorder) ListTodos(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodos", reflect.TypeOf((*MockTodoServiceClient)(nil).ListTodos), varargs...)
}

// PostTodo mocks base method.
func (m *MockTodoServiceClient) PostTodo(ctx context.Context, in *v1.PostTodoRequest, opts ...grpc.CallOption) (*v1.PostTodoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostTodo", varargs...)
	ret0, _ := ret[0].(*v1.PostTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTodo indicates an expected call of PostTodo.
func (mr *MockTodoServiceClientMockRecorder) PostTodo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTodo", reflect.TypeOf((*MockTodoServiceClient)(nil).PostTodo), varargs...)
}

// PostUser mocks base method.
func (m *MockTodoServiceClient) PostUser(ctx context.Context, in *v1.PostUserRequest, opts ...grpc.CallOption) (*v1.PostUserResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PostUser", varargs...)
	ret0, _ := ret[0].(*v1.PostUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostUser indicates an expected call of PostUser.
func (mr *MockTodoServiceClientMockRecorder) PostUser(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUser", reflect.TypeOf((*MockTodoServiceClient)(nil).PostUser), varargs...)
}

// PutTodo mocks base method.
func (m *MockTodoServiceClient) PutTodo(ctx context.Context, in *v1.PutTodoRequest, opts ...grpc.CallOption) (*v1.PutTodoResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutTodo", varargs...)
	ret0, _ := ret[0].(*v1.PutTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutTodo indicates an expected call of PutTodo.
func (mr *MockTodoServiceClientMockRecorder) PutTodo(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTodo", reflect.TypeOf((*MockTodoServiceClient)(nil).PutTodo), varargs...)
}

// MockTodoServiceServer is a mock of TodoServiceServer interface.
type MockTodoServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockTodoServiceServerMockRecorder
	isgomock struct{}
}

// MockTodoServiceServerMockRecorder is the mock recorder for MockTodoServiceServer.
type MockTodoServiceServerMockRecorder struct {
	mock *MockTodoServiceServer
}

// NewMockTodoServiceServer creates a new mock instance.
func NewMockTodoServiceServer(ctrl *gomock.Controller) *MockTodoServiceServer {
	mock := &MockTodoServiceServer{ctrl: ctrl}
	mock.recorder = &MockTodoServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoServiceServer) EXPECT() *MockTodoServiceServerMockRecorder {
	return m.recorder
}

// DeleteTodo mocks base method.
func (m *MockTodoServiceServer) DeleteTodo(arg0 context.Context, arg1 *v1.DeleteTodoRequest) (*v1.DeleteTodoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTodo", arg0, arg1)
	ret0, _ := ret[0].(*v1.DeleteTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteTodo indicates an expected call of DeleteTodo.
func (mr *MockTodoServiceServerMockRecorder) DeleteTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTodo", reflect.TypeOf((*MockTodoServiceServer)(nil).DeleteTodo), arg0, arg1)
}

// GetTodo mocks base method.
func (m *MockTodoServiceServer) GetTodo(arg0 context.Context, arg1 *v1.GetTodoRequest) (*v1.GetTodoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTodo", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTodo indicates an expected call of GetTodo.
func (mr *MockTodoServiceServerMockRecorder) GetTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTodo", reflect.TypeOf((*MockTodoServiceServer)(nil).GetTodo), arg0, arg1)
}

// GetUser mocks base method.
func (m *MockTodoServiceServer) GetUser(arg0 context.Context, arg1 *v1.GetUserRequest) (*v1.GetUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0, arg1)
	ret0, _ := ret[0].(*v1.GetUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockTodoServiceServerMockRecorder) GetUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockTodoServiceServer)(nil).GetUser), arg0, arg1)
}

// ListTodos mocks base method.
func (m *MockTodoServiceServer) ListTodos(arg0 context.Context, arg1 *v1.ListTodosRequest) (*v1.ListTodosResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTodos", arg0, arg1)
	ret0, _ := ret[0].(*v1.ListTodosResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTodos indicates an expected call of ListTodos.
func (mr *MockTodoServiceServerMockRecorder) ListTodos(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTodos", reflect.TypeOf((*MockTodoServiceServer)(nil).ListTodos), arg0, arg1)
}

// PostTodo mocks base method.
func (m *MockTodoServiceServer) PostTodo(arg0 context.Context, arg1 *v1.PostTodoRequest) (*v1.PostTodoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostTodo", arg0, arg1)
	ret0, _ := ret[0].(*v1.PostTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostTodo indicates an expected call of PostTodo.
func (mr *MockTodoServiceServerMockRecorder) PostTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostTodo", reflect.TypeOf((*MockTodoServiceServer)(nil).PostTodo), arg0, arg1)
}

// PostUser mocks base method.
func (m *MockTodoServiceServer) PostUser(arg0 context.Context, arg1 *v1.PostUserRequest) (*v1.PostUserResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostUser", arg0, arg1)
	ret0, _ := ret[0].(*v1.PostUserResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostUser indicates an expected call of PostUser.
func (mr *MockTodoServiceServerMockRecorder) PostUser(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostUser", reflect.TypeOf((*MockTodoServiceServer)(nil).PostUser), arg0, arg1)
}

// PutTodo mocks base method.
func (m *MockTodoServiceServer) PutTodo(arg0 context.Context, arg1 *v1.PutTodoRequest) (*v1.PutTodoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutTodo", arg0, arg1)
	ret0, _ := ret[0].(*v1.PutTodoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutTodo indicates an expected call of PutTodo.
func (mr *MockTodoServiceServerMockRecorder) PutTodo(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutTodo", reflect.TypeOf((*MockTodoServiceServer)(nil).PutTodo), arg0, arg1)
}

// mustEmbedUnimplementedTodoServiceServer mocks base method.
func (m *MockTodoServiceServer) mustEmbedUnimplementedTodoServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTodoServiceServer")
}

// mustEmbedUnimplementedTodoServiceServer indicates an expected call of mustEmbedUnimplementedTodoServiceServer.
func (mr *MockTodoServiceServerMockRecorder) mustEmbedUnimplementedTodoServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTodoServiceServer", reflect.TypeOf((*MockTodoServiceServer)(nil).mustEmbedUnimplementedTodoServiceServer))
}

// MockUnsafeTodoServiceServer is a mock of UnsafeTodoServiceServer interface.
type MockUnsafeTodoServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeTodoServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeTodoServiceServerMockRecorder is the mock recorder for MockUnsafeTodoServiceServer.
type MockUnsafeTodoServiceServerMockRecorder struct {
	mock *MockUnsafeTodoServiceServer
}

// NewMockUnsafeTodoServiceServer creates a new mock instance.
func NewMockUnsafeTodoServiceServer(ctrl *gomock.Controller) *MockUnsafeTodoServiceServer {
	mock := &MockUnsafeTodoServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeTodoServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeTodoServiceServer) EXPECT() *MockUnsafeTodoServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedTodoServiceServer mocks base method.
func (m *MockUnsafeTodoServiceServer) mustEmbedUnimplementedTodoServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedTodoServiceServer")
}

// mustEmbedUnimplementedTodoServiceServer indicates an expected call of mustEmbedUnimplementedTodoServiceServer.
func (mr *MockUnsafeTodoServiceServerMockRecorder) mustEmbedUnimplementedTodoServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedTodoServiceServer", reflect.TypeOf((*MockUnsafeTodoServiceServer)(nil).mustEmbedUnimplementedTodoServiceServer))
}
