// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/gateway.go -destination=internal/domain/gateway/mock/gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/phamquanandpad/training-project/go/services/todo-bff/internal/domain/model/auth"
	todo "github.com/phamquanandpad/training-project/go/services/todo-bff/internal/domain/model/todo"
	gomock "go.uber.org/mock/gomock"
)

// MockBinder is a mock of Binder interface.
type MockBinder struct {
	ctrl     *gomock.Controller
	recorder *MockBinderMockRecorder
	isgomock struct{}
}

// MockBinderMockRecorder is the mock recorder for MockBinder.
type MockBinderMockRecorder struct {
	mock *MockBinder
}

// NewMockBinder creates a new mock instance.
func NewMockBinder(ctrl *gomock.Controller) *MockBinder {
	mock := &MockBinder{ctrl: ctrl}
	mock.recorder = &MockBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinder) EXPECT() *MockBinderMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockBinder) Bind(ctx context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", ctx)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockBinderMockRecorder) Bind(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockBinder)(nil).Bind), ctx)
}

// MockTodoQueriesGateway is a mock of TodoQueriesGateway interface.
type MockTodoQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockTodoQueriesGatewayMockRecorder is the mock recorder for MockTodoQueriesGateway.
type MockTodoQueriesGatewayMockRecorder struct {
	mock *MockTodoQueriesGateway
}

// NewMockTodoQueriesGateway creates a new mock instance.
func NewMockTodoQueriesGateway(ctrl *gomock.Controller) *MockTodoQueriesGateway {
	mock := &MockTodoQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockTodoQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoQueriesGateway) EXPECT() *MockTodoQueriesGatewayMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockTodoQueriesGateway) Get(ctx context.Context, userAttributes todo.UserAttributes, todoID todo.TodoID) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userAttributes, todoID)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTodoQueriesGatewayMockRecorder) Get(ctx, userAttributes, todoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTodoQueriesGateway)(nil).Get), ctx, userAttributes, todoID)
}

// List mocks base method.
func (m *MockTodoQueriesGateway) List(ctx context.Context, userAttributes todo.UserAttributes, limit, offset int) ([]*todo.Todo, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userAttributes, limit, offset)
	ret0, _ := ret[0].([]*todo.Todo)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockTodoQueriesGatewayMockRecorder) List(ctx, userAttributes, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTodoQueriesGateway)(nil).List), ctx, userAttributes, limit, offset)
}

// MockTodoCommandsGateway is a mock of TodoCommandsGateway interface.
type MockTodoCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockTodoCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockTodoCommandsGatewayMockRecorder is the mock recorder for MockTodoCommandsGateway.
type MockTodoCommandsGatewayMockRecorder struct {
	mock *MockTodoCommandsGateway
}

// NewMockTodoCommandsGateway creates a new mock instance.
func NewMockTodoCommandsGateway(ctrl *gomock.Controller) *MockTodoCommandsGateway {
	mock := &MockTodoCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockTodoCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoCommandsGateway) EXPECT() *MockTodoCommandsGatewayMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTodoCommandsGateway) Create(ctx context.Context, userAttributes todo.UserAttributes, newTodo todo.NewTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userAttributes, newTodo)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTodoCommandsGatewayMockRecorder) Create(ctx, userAttributes, newTodo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTodoCommandsGateway)(nil).Create), ctx, userAttributes, newTodo)
}

// Delete mocks base method.
func (m *MockTodoCommandsGateway) Delete(ctx context.Context, userAttributes todo.UserAttributes, todoID todo.TodoID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userAttributes, todoID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTodoCommandsGatewayMockRecorder) Delete(ctx, userAttributes, todoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTodoCommandsGateway)(nil).Delete), ctx, userAttributes, todoID)
}

// Update mocks base method.
func (m *MockTodoCommandsGateway) Update(ctx context.Context, userAttributes todo.UserAttributes, todoID todo.TodoID, updateTodo todo.UpdateTodo) (*todo.Todo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, userAttributes, todoID, updateTodo)
	ret0, _ := ret[0].(*todo.Todo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTodoCommandsGatewayMockRecorder) Update(ctx, userAttributes, todoID, updateTodo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTodoCommandsGateway)(nil).Update), ctx, userAttributes, todoID, updateTodo)
}

// MockAuthReaderGateway is a mock of AuthReaderGateway interface.
type MockAuthReaderGateway struct {
	ctrl     *gomock.Controller
	recorder *MockAuthReaderGatewayMockRecorder
	isgomock struct{}
}

// MockAuthReaderGatewayMockRecorder is the mock recorder for MockAuthReaderGateway.
type MockAuthReaderGatewayMockRecorder struct {
	mock *MockAuthReaderGateway
}

// NewMockAuthReaderGateway creates a new mock instance.
func NewMockAuthReaderGateway(ctrl *gomock.Controller) *MockAuthReaderGateway {
	mock := &MockAuthReaderGateway{ctrl: ctrl}
	mock.recorder = &MockAuthReaderGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthReaderGateway) EXPECT() *MockAuthReaderGatewayMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthReaderGateway) Login(ctx context.Context, email, password string) (*auth.Tokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(*auth.Tokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockAuthReaderGatewayMockRecorder) Login(ctx, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthReaderGateway)(nil).Login), ctx, email, password)
}

// RefreshToken mocks base method.
func (m *MockAuthReaderGateway) RefreshToken(ctx context.Context, refreshToken string) (*auth.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx, refreshToken)
	ret0, _ := ret[0].(*auth.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockAuthReaderGatewayMockRecorder) RefreshToken(ctx, refreshToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockAuthReaderGateway)(nil).RefreshToken), ctx, refreshToken)
}

// Register mocks base method.
func (m *MockAuthReaderGateway) Register(ctx context.Context, username, email, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, username, email, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockAuthReaderGatewayMockRecorder) Register(ctx, username, email, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthReaderGateway)(nil).Register), ctx, username, email, password)
}

// VerifyToken mocks base method.
func (m *MockAuthReaderGateway) VerifyToken(ctx context.Context, accessToken string) (*auth.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyToken", ctx, accessToken)
	ret0, _ := ret[0].(*auth.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyToken indicates an expected call of VerifyToken.
func (mr *MockAuthReaderGatewayMockRecorder) VerifyToken(ctx, accessToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyToken", reflect.TypeOf((*MockAuthReaderGateway)(nil).VerifyToken), ctx, accessToken)
}

// MockSessionQueriesGateway is a mock of SessionQueriesGateway interface.
type MockSessionQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockSessionQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockSessionQueriesGatewayMockRecorder is the mock recorder for MockSessionQueriesGateway.
type MockSessionQueriesGatewayMockRecorder struct {
	mock *MockSessionQueriesGateway
}

// NewMockSessionQueriesGateway creates a new mock instance.
func NewMockSessionQueriesGateway(ctrl *gomock.Controller) *MockSessionQueriesGateway {
	mock := &MockSessionQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockSessionQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionQueriesGateway) EXPECT() *MockSessionQueriesGatewayMockRecorder {
	return m.recorder
}

// GetAccessToken mocks base method.
func (m *MockSessionQueriesGateway) GetAccessToken(ctx context.Context, sessionID string) (*auth.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessToken", ctx, sessionID)
	ret0, _ := ret[0].(*auth.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessToken indicates an expected call of GetAccessToken.
func (mr *MockSessionQueriesGatewayMockRecorder) GetAccessToken(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessToken", reflect.TypeOf((*MockSessionQueriesGateway)(nil).GetAccessToken), ctx, sessionID)
}

// MockSessionCommandsGateway is a mock of SessionCommandsGateway interface.
type MockSessionCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockSessionCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockSessionCommandsGatewayMockRecorder is the mock recorder for MockSessionCommandsGateway.
type MockSessionCommandsGatewayMockRecorder struct {
	mock *MockSessionCommandsGateway
}

// NewMockSessionCommandsGateway creates a new mock instance.
func NewMockSessionCommandsGateway(ctrl *gomock.Controller) *MockSessionCommandsGateway {
	mock := &MockSessionCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockSessionCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionCommandsGateway) EXPECT() *MockSessionCommandsGatewayMockRecorder {
	return m.recorder
}

// DeleteSession mocks base method.
func (m *MockSessionCommandsGateway) DeleteSession(ctx context.Context, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockSessionCommandsGatewayMockRecorder) DeleteSession(ctx, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockSessionCommandsGateway)(nil).DeleteSession), ctx, sessionID)
}

// SetAccessToken mocks base method.
func (m *MockSessionCommandsGateway) SetAccessToken(ctx context.Context, sessionID, refreshToken string, expireSecond int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAccessToken", ctx, sessionID, refreshToken, expireSecond)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAccessToken indicates an expected call of SetAccessToken.
func (mr *MockSessionCommandsGatewayMockRecorder) SetAccessToken(ctx, sessionID, refreshToken, expireSecond any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAccessToken", reflect.TypeOf((*MockSessionCommandsGateway)(nil).SetAccessToken), ctx, sessionID, refreshToken, expireSecond)
}
