// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/go-playground/validator/v10"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/config"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/domain/service"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/handler"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/handler/requestbinder"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/infrastructure/datastore"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/infrastructure/jwt"
	"github.com/phamquanandpad/training-project/go/services/auth/internal/infrastructure/todo"
	"github.com/phamquanandpad/training-project/grpc/go/auth/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"
	"time"
)

// Injectors from wire.go:

func InitializeServer(c *config.Config, v *validator.Validate) (*grpc.Server, func(), error) {
	requestBinder := requestbinder.NewRequestBinder(v)
	dbConfig := newDBConfig(c)
	todoConn, cleanup, err := datastore.NewTodoSQLHandler(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	binder := datastore.NewConnectionBinder(todoConn)
	userQueriesGateway := datastore.NewUserReader()
	jwtConfig := newJwtConfig(c)
	jwtGenerateGateway := jwt.NewTokenGenerator(jwtConfig)
	userLogin := service.NewUserLogin(binder, userQueriesGateway, jwtGenerateGateway)
	userCommandsGateway := datastore.NewUserWriter()
	todoConnection, cleanup2, err := todo.NewTodoServiceConnection(c)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	todoServiceClient := todo.NewTodoServiceClient(todoConnection)
	userServiceCommandsGateway := todo.NewUserWriter(todoServiceClient)
	userRegister := service.NewUserRegister(binder, userCommandsGateway, userQueriesGateway, userServiceCommandsGateway)
	jwtVerifyGateway := jwt.NewTokenVerifier(jwtConfig)
	tokenVerify := service.NewTokenVerify(binder, jwtVerifyGateway, userQueriesGateway)
	tokenRefresh := service.NewTokenRefresh(binder, jwtGenerateGateway, jwtVerifyGateway, userQueriesGateway)
	authServiceServer, err := handler.NewAuthService(c, v, requestBinder, userLogin, userRegister, tokenVerify, tokenRefresh)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := NewGRPCServer(authServiceServer, c)
	return server, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func NewGRPCServer(
	authServiceServer auth_v1.AuthServiceServer,
	conf *config.Config,
) *grpc.Server {

	server := grpc.NewServer(grpc.KeepaliveParams(keepalive.ServerParameters{
		Time:              150 * time.Second,
		MaxConnectionIdle: 10 * time.Minute,
	}), grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
		MinTime: 1 * time.Minute,
	}),
	)
	auth_v1.RegisterAuthServiceServer(server, authServiceServer)

	return server
}

func newDBConfig(conf *config.Config) *config.DBConfig {
	return &config.DBConfig{
		DBHost: conf.DBHost,
		DBPort: conf.DBPort,
		DBUser: conf.DBUser,
		DBPass: conf.DBPass,
		DBName: conf.DBName,
	}
}

func newJwtConfig(conf *config.Config) *config.JwtConfig {
	return &config.JwtConfig{
		AccessTokenSecret:         conf.AccessTokenSecret,
		RefreshTokenSecret:        conf.RefreshTokenSecret,
		AccessTokenExpiresSecond:  conf.AccessTokenExpiresSecond,
		RefreshTokenExpiresSecond: conf.RefreshTokenExpiresSecond,
	}
}
