services:
  database:
    image: mysql:8.4
    container_name: auth_database
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    networks:
      - auth_network
    ports:
      - "33061:3306"
    volumes:
      - ./database/docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./database/docker/sqls:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-udocker", "-pdocker"]
      interval: 5s
      timeout: 5s
      retries: 20

  dbmigrate:
    image: golang:1.25-alpine
    container_name: auth_dbmigration
    depends_on:
      database:
        condition: service_healthy
    working_dir: /workspace/go
    command: ["sh", "-c", "go run ./services/auth/cmd/migrate up"]
    environment:
      DB_HOST: database
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: password
      DB_NAME: auth
    networks:
      - auth_network
    volumes:
      - ../..:/workspace/go
      - ./database/migrations:/workspace/go/database/migrations
    restart: "no"

networks:
  auth_network:
