// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package registry

import (
	"github.com/go-playground/validator/v10"
	"github.com/grpc-ecosystem/go-grpc-middleware"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/config"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/domain/service"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/handler"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/handler/interceptor/datavalidator"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/handler/requestbinder"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/infrastructure/datastore"
	"github.com/phamquanandpad/training-project/go/services/todo/internal/usecase"
	"github.com/phamquanandpad/training-project/grpc/go/todo/todo/v1"
	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"
	"time"
)

// Injectors from wire.go:

func InitializeServer(conf *config.Config, validate *validator.Validate) (*grpc.Server, func(), error) {
	requestBinder := requestbinder.NewRequestBinder(validate)
	dbConfig := newDBConfig(conf)
	todoConn, cleanup, err := datastore.NewTodoSQLHandler(dbConfig)
	if err != nil {
		return nil, nil, err
	}
	binder := datastore.NewConnectionBinder(todoConn)
	todoQueriesGateway := datastore.NewTodoReader()
	todoGetter := service.NewTodoGetter(binder, todoQueriesGateway)
	todoLister := service.NewTodoLister(binder, todoQueriesGateway)
	todoCommandsGateway := datastore.NewTodoWriter()
	todoCreator := service.NewTodoCreator(binder, todoCommandsGateway)
	todoHelper := service.NewTodoHelper(todoQueriesGateway)
	todoUpdater := service.NewTodoUpdater(binder, todoCommandsGateway, todoHelper)
	todoDeleter := service.NewTodoDeleter(binder, todoCommandsGateway, todoHelper)
	userQueriesGateway := datastore.NewUserReader()
	userGetter := service.NewUserGetter(binder, userQueriesGateway)
	userCommandsGateway := datastore.NewUserWriter()
	userCreator := service.NewUserCreator(binder, userCommandsGateway)
	todoServiceServer, err := handler.NewTodoService(conf, validate, requestBinder, todoGetter, todoLister, todoCreator, todoUpdater, todoDeleter, userGetter, userCreator)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataValidator := service.NewDataValidator(binder, userQueriesGateway)
	server := NewGRPCServer(todoServiceServer, dataValidator, conf)
	return server, func() {
		cleanup()
	}, nil
}

// wire.go:

func NewGRPCServer(
	todoServiceServer todo_todo_v1.TodoServiceServer,
	dataValidator usecase.DataValidator,
	conf *config.Config,
) *grpc.Server {
	server := grpc.NewServer(grpc.UnaryInterceptor(grpc_middleware.ChainUnaryServer(datavalidator.UnaryServerInterceptor(dataValidator)),
	), grpc.KeepaliveParams(keepalive.ServerParameters{
		Time:              150 * time.Second,
		MaxConnectionIdle: 10 * time.Minute,
	}), grpc.KeepaliveEnforcementPolicy(keepalive.EnforcementPolicy{
		MinTime: 1 * time.Minute,
	}),
	)
	todo_todo_v1.RegisterTodoServiceServer(server, todoServiceServer)

	return server
}

func newDBConfig(conf *config.Config) *config.DBConfig {
	return &config.DBConfig{
		DBHost: conf.DBHost,
		DBPort: conf.DBPort,
		DBUser: conf.DBUser,
		DBPass: conf.DBPass,
		DBName: conf.DBName,
	}
}
