package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.87

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	app_errors "github.com/phamquanandpad/training-project/go/services/todo-bff/internal/errors"

	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/domain/model/todo"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/handler/graph/generated"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/handler/graph/model"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/middleware"
	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/usecase/input"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, in model.PostTodoRequest) (*todo.Todo, error) {
	userID := middleware.UserIDFromContext(ctx)

	status := mapModelStatusToDomain(in.Status)
	out, err := r.todoCreator.CreateTodo(ctx, &input.TodoCreator{
		UserID:      todo.UserID(userID.Int64()),
		Task:        in.Task,
		Description: in.Description,
		Status:      status,
	})
	if err != nil {
		return nil, err
	}
	return out.Todo, nil
}

// UpdateTodo is the resolver for the updateTodo field.
func (r *mutationResolver) UpdateTodo(ctx context.Context, in model.PutTodoRequest) (*todo.Todo, error) {
	userID := middleware.UserIDFromContext(ctx)

	id, err := strconv.ParseInt(in.ID, 10, 64)
	if err != nil {
		return nil, app_errors.NewParameterError(
			"handler.graph.schema.resolvers",
			err,
			&app_errors.LocalizedMessage{JaMessage: app_errors.ParameterErrorJaMessage},
		)
	}
	var status *todo.TodoStatus
	if in.Status != nil {
		s := mapModelStatusToDomain(*in.Status)
		status = &s
	}
	out, err := r.todoUpdater.UpdateTodo(ctx, &input.TodoUpdater{
		UserID:      todo.UserID(userID.Int64()),
		ID:          todo.TodoID(id),
		Task:        in.Task,
		Description: in.Description,
		Status:      status,
	})
	if err != nil {
		return nil, err
	}
	return out.Todo, nil
}

// DeleteTodo is the resolver for the deleteTodo field.
func (r *mutationResolver) DeleteTodo(ctx context.Context, in model.DeleteTodoRequest) (bool, error) {
	userID := middleware.UserIDFromContext(ctx)

	id, err := strconv.ParseInt(in.ID, 10, 64)
	if err != nil {
		return false, app_errors.NewParameterError(
			"handler.graph.schema.resolvers",
			err,
			&app_errors.LocalizedMessage{JaMessage: app_errors.ParameterErrorJaMessage},
		)
	}
	err = r.todoDeleter.DeleteTodo(ctx, &input.TodoDeleter{
		UserID: todo.UserID(userID.Int64()),
		ID:     todo.TodoID(id),
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, in model.LoginRequest) (bool, error) {
	out, err := r.userLogin.Login(ctx, &input.UserLogin{
		Email:    in.Email,
		Password: in.Password,
	})
	if err != nil {
		return false, err
	}

	w, ok := middleware.ResponseWriterFromContext(ctx)
	if !ok {
		return false, app_errors.NewInternalError(
			"handler.graph.schema.resolvers",
			fmt.Errorf("cannot get response writer"),
		)
	}

	http.SetCookie(w, &http.Cookie{
		Name:     middleware.AccessTokenCookieKey,
		Value:    out.Tokens.AccessToken.Token,
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteStrictMode,
		Path:     "/",
	})
	http.SetCookie(w, &http.Cookie{
		Name:     middleware.RefreshTokenCookieKey,
		Value:    out.Tokens.RefreshToken.Token,
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteStrictMode,
		Path:     "/auth/refresh",
	})

	return true, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, in model.RegisterRequest) (bool, error) {
	err := r.userRegister.Register(ctx, &input.UserRegister{
		Username: in.Username,
		Email:    in.Email,
		Password: in.Password,
	})
	if err != nil {
		return false, err
	}
	return true, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (bool, error) {
	token := middleware.RefreshTokenFromContext(ctx)
	if token == "" {
		return false, app_errors.NewAuthNError(
			"handler.graph.schema.resolvers",
			fmt.Errorf("refresh token not found in context"),
			&app_errors.LocalizedMessage{JaMessage: app_errors.AuthNJaMessage},
		)
	}

	out, err := r.tokenRefresh.RefreshToken(ctx, &input.TokenRefresh{
		RefreshToken: token,
	})
	if err != nil {
		return false, err
	}

	w, ok := middleware.ResponseWriterFromContext(ctx)
	if !ok {
		return false, app_errors.NewInternalError(
			"handler.graph.schema.resolvers",
			fmt.Errorf("cannot get response writer"),
		)
	}

	http.SetCookie(w, &http.Cookie{
		Name:     middleware.AccessTokenCookieKey,
		Value:    out.AccessToken.Token,
		HttpOnly: true,
		Secure:   true,
		SameSite: http.SameSiteStrictMode,
		Path:     "/",
	})

	return true, nil
}

// GetTodo is the resolver for the getTodo field.
func (r *queryResolver) GetTodo(ctx context.Context, in model.GetTodoRequest) (*todo.Todo, error) {
	userID := middleware.UserIDFromContext(ctx)
	id, err := strconv.ParseInt(in.ID, 10, 64)
	if err != nil {
		return nil, app_errors.NewParameterError(
			"handler.graph.schema.resolvers",
			err,
			&app_errors.LocalizedMessage{JaMessage: app_errors.ParameterErrorJaMessage},
		)
	}
	out, err := r.todoGetter.GetTodo(ctx, &input.TodoGetter{
		UserID: todo.UserID(userID.Int64()),
		ID:     todo.TodoID(id),
	})
	if err != nil {
		return nil, err
	}
	return out.Todo, nil
}

// ListTodo is the resolver for the listTodo field.
func (r *queryResolver) ListTodo(ctx context.Context, in model.ListTodosRequest) (*model.ListTodosResponse, error) {
	userID := middleware.UserIDFromContext(ctx)
	out, err := r.todoLister.ListTodos(ctx, &input.TodoLister{
		UserID: todo.UserID(userID.Int64()),
		Limit:  int(in.Limit),
		Offset: int(in.Offset),
	})
	if err != nil {
		return nil, err
	}
	return &model.ListTodosResponse{
		Todos: out.Todos,
		Total: int32(out.TotalCount),
	}, nil
}

// ID is the resolver for the id field.
func (r *todoResolver) ID(ctx context.Context, obj *todo.Todo) (string, error) {
	return obj.ID.String(), nil
}

// Status is the resolver for the status field.
func (r *todoResolver) Status(ctx context.Context, obj *todo.Todo) (model.TodoStatus, error) {
	return mapDomainStatusToModel(obj.Status), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Todo returns generated.TodoResolver implementation.
func (r *Resolver) Todo() generated.TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }

func mapModelStatusToDomain(s model.TodoStatus) todo.TodoStatus {
	switch s {
	case model.TodoStatusInProcess:
		return todo.InProcess
	case model.TodoStatusDone:
		return todo.Done
	default:
		return todo.Pending
	}
}
func mapDomainStatusToModel(s todo.TodoStatus) model.TodoStatus {
	switch s {
	case todo.InProcess:
		return model.TodoStatusInProcess
	case todo.Done:
		return model.TodoStatusDone
	default:
		return model.TodoStatusPending
	}
}
