// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: todo/common/v1/todo_model.proto

package todo_common_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TodoStatus int32

const (
	TodoStatus_TODO_STATUS_PENDING   TodoStatus = 0
	TodoStatus_TODO_STATUS_INPROCESS TodoStatus = 1
	TodoStatus_TODO_STATUS_DONE      TodoStatus = 2
)

// Enum value maps for TodoStatus.
var (
	TodoStatus_name = map[int32]string{
		0: "TODO_STATUS_PENDING",
		1: "TODO_STATUS_INPROCESS",
		2: "TODO_STATUS_DONE",
	}
	TodoStatus_value = map[string]int32{
		"TODO_STATUS_PENDING":   0,
		"TODO_STATUS_INPROCESS": 1,
		"TODO_STATUS_DONE":      2,
	}
)

func (x TodoStatus) Enum() *TodoStatus {
	p := new(TodoStatus)
	*p = x
	return p
}

func (x TodoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TodoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_todo_common_v1_todo_model_proto_enumTypes[0].Descriptor()
}

func (TodoStatus) Type() protoreflect.EnumType {
	return &file_todo_common_v1_todo_model_proto_enumTypes[0]
}

func (x TodoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TodoStatus.Descriptor instead.
func (TodoStatus) EnumDescriptor() ([]byte, []int) {
	return file_todo_common_v1_todo_model_proto_rawDescGZIP(), []int{0}
}

type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Task          string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        TodoStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=todo.common.v1.TodoStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todo_common_v1_todo_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_common_v1_todo_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todo_common_v1_todo_model_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Todo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Todo) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetStatus() TodoStatus {
	if x != nil {
		return x.Status
	}
	return TodoStatus_TODO_STATUS_PENDING
}

func (x *Todo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Todo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_todo_common_v1_todo_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_todo_common_v1_todo_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_todo_common_v1_todo_model_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

var File_todo_common_v1_todo_model_proto protoreflect.FileDescriptor

const file_todo_common_v1_todo_model_proto_rawDesc = "" +
	"\n" +
	"\x1ftodo/common/v1/todo_model.proto\x12\x0etodo.common.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8f\x02\n" +
	"\x04Todo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.todo.common.v1.TodoStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xbe\x01\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt*V\n" +
	"\n" +
	"TodoStatus\x12\x17\n" +
	"\x13TODO_STATUS_PENDING\x10\x00\x12\x19\n" +
	"\x15TODO_STATUS_INPROCESS\x10\x01\x12\x14\n" +
	"\x10TODO_STATUS_DONE\x10\x02BRZPgithub.com/phamquanandpad/training-project/grpc/go/todo/common/v1;todo_common_v1b\x06proto3"

var (
	file_todo_common_v1_todo_model_proto_rawDescOnce sync.Once
	file_todo_common_v1_todo_model_proto_rawDescData []byte
)

func file_todo_common_v1_todo_model_proto_rawDescGZIP() []byte {
	file_todo_common_v1_todo_model_proto_rawDescOnce.Do(func() {
		file_todo_common_v1_todo_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_common_v1_todo_model_proto_rawDesc), len(file_todo_common_v1_todo_model_proto_rawDesc)))
	})
	return file_todo_common_v1_todo_model_proto_rawDescData
}

var file_todo_common_v1_todo_model_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_todo_common_v1_todo_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_todo_common_v1_todo_model_proto_goTypes = []any{
	(TodoStatus)(0),               // 0: todo.common.v1.TodoStatus
	(*Todo)(nil),                  // 1: todo.common.v1.Todo
	(*User)(nil),                  // 2: todo.common.v1.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_todo_common_v1_todo_model_proto_depIdxs = []int32{
	0, // 0: todo.common.v1.Todo.status:type_name -> todo.common.v1.TodoStatus
	3, // 1: todo.common.v1.Todo.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: todo.common.v1.Todo.updated_at:type_name -> google.protobuf.Timestamp
	3, // 3: todo.common.v1.User.created_at:type_name -> google.protobuf.Timestamp
	3, // 4: todo.common.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_todo_common_v1_todo_model_proto_init() }
func file_todo_common_v1_todo_model_proto_init() {
	if File_todo_common_v1_todo_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_common_v1_todo_model_proto_rawDesc), len(file_todo_common_v1_todo_model_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_common_v1_todo_model_proto_goTypes,
		DependencyIndexes: file_todo_common_v1_todo_model_proto_depIdxs,
		EnumInfos:         file_todo_common_v1_todo_model_proto_enumTypes,
		MessageInfos:      file_todo_common_v1_todo_model_proto_msgTypes,
	}.Build()
	File_todo_common_v1_todo_model_proto = out.File
	file_todo_common_v1_todo_model_proto_goTypes = nil
	file_todo_common_v1_todo_model_proto_depIdxs = nil
}
