// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/phamquanandpad/training-project/go/services/todo-bff/internal/domain/model/todo"
)

type DeleteTodoRequest struct {
	ID string `json:"id"`
}

type GetTodoRequest struct {
	ID string `json:"id"`
}

type ListTodosRequest struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListTodosResponse struct {
	Todos []*todo.Todo `json:"todos,omitempty"`
	Total int32        `json:"total"`
}

type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type PostTodoRequest struct {
	Task        string     `json:"task"`
	Description *string    `json:"description,omitempty"`
	Status      TodoStatus `json:"status"`
}

type PutTodoRequest struct {
	ID          string      `json:"id"`
	Task        *string     `json:"task,omitempty"`
	Description *string     `json:"description,omitempty"`
	Status      *TodoStatus `json:"status,omitempty"`
}

type Query struct {
}

type RegisterRequest struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type TodoStatus string

const (
	TodoStatusPending   TodoStatus = "PENDING"
	TodoStatusInProcess TodoStatus = "IN_PROCESS"
	TodoStatusDone      TodoStatus = "DONE"
)

var AllTodoStatus = []TodoStatus{
	TodoStatusPending,
	TodoStatusInProcess,
	TodoStatusDone,
}

func (e TodoStatus) IsValid() bool {
	switch e {
	case TodoStatusPending, TodoStatusInProcess, TodoStatusDone:
		return true
	}
	return false
}

func (e TodoStatus) String() string {
	return string(e)
}

func (e *TodoStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TodoStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TodoStatus", str)
	}
	return nil
}

func (e TodoStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TodoStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TodoStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
