// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: todo/todo/v1/auth.proto

package todo_todo_v1

import (
	v1 "github.com/phamquanandpad/training-project/grpc/go/todo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_todo_todo_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccessToken         string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken        string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessTokenExpires  int64                  `protobuf:"varint,3,opt,name=access_token_expires,json=accessTokenExpires,proto3" json:"access_token_expires,omitempty"`
	RefreshTokenExpires int64                  `protobuf:"varint,4,opt,name=refresh_token_expires,json=refreshTokenExpires,proto3" json:"refresh_token_expires,omitempty"`
	User                *v1.User               `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_todo_todo_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LoginResponse) GetAccessTokenExpires() int64 {
	if x != nil {
		return x.AccessTokenExpires
	}
	return 0
}

func (x *LoginResponse) GetRefreshTokenExpires() int64 {
	if x != nil {
		return x.RefreshTokenExpires
	}
	return 0
}

func (x *LoginResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_todo_todo_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_todo_todo_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_todo_todo_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	AccessTokenExpires int64                  `protobuf:"varint,2,opt,name=access_token_expires,json=accessTokenExpires,proto3" json:"access_token_expires,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RefreshResponse) Reset() {
	*x = RefreshResponse{}
	mi := &file_todo_todo_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshResponse) ProtoMessage() {}

func (x *RefreshResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshResponse.ProtoReflect.Descriptor instead.
func (*RefreshResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *RefreshResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshResponse) GetAccessTokenExpires() int64 {
	if x != nil {
		return x.AccessTokenExpires
	}
	return 0
}

var File_todo_todo_v1_auth_proto protoreflect.FileDescriptor

const file_todo_todo_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x17todo/todo/v1/auth.proto\x12\ftodo.todo.v1\x1a\x1ftodo/common/v1/todo_model.proto\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xe7\x01\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\x120\n" +
	"\x14access_token_expires\x18\x03 \x01(\x03R\x12accessTokenExpires\x122\n" +
	"\x15refresh_token_expires\x18\x04 \x01(\x03R\x13refreshTokenExpires\x12(\n" +
	"\x04user\x18\x05 \x01(\v2\x14.todo.common.v1.UserR\x04user\"_\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\"<\n" +
	"\x10RegisterResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.todo.common.v1.UserR\x04user\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"f\n" +
	"\x0fRefreshResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x120\n" +
	"\x14access_token_expires\x18\x02 \x01(\x03R\x12accessTokenExpires2\xe8\x01\n" +
	"\vAuthService\x12B\n" +
	"\x05Login\x12\x1a.todo.todo.v1.LoginRequest\x1a\x1b.todo.todo.v1.LoginResponse\"\x00\x12K\n" +
	"\bRegister\x12\x1d.todo.todo.v1.RegisterRequest\x1a\x1e.todo.todo.v1.RegisterResponse\"\x00\x12H\n" +
	"\aRefresh\x12\x1c.todo.todo.v1.RefreshRequest\x1a\x1d.todo.todo.v1.RefreshResponse\"\x00B\x1bZ\x19todo/todo/v1;todo_todo_v1b\x06proto3"

var (
	file_todo_todo_v1_auth_proto_rawDescOnce sync.Once
	file_todo_todo_v1_auth_proto_rawDescData []byte
)

func file_todo_todo_v1_auth_proto_rawDescGZIP() []byte {
	file_todo_todo_v1_auth_proto_rawDescOnce.Do(func() {
		file_todo_todo_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_todo_v1_auth_proto_rawDesc), len(file_todo_todo_v1_auth_proto_rawDesc)))
	})
	return file_todo_todo_v1_auth_proto_rawDescData
}

var file_todo_todo_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_todo_todo_v1_auth_proto_goTypes = []any{
	(*LoginRequest)(nil),     // 0: todo.todo.v1.LoginRequest
	(*LoginResponse)(nil),    // 1: todo.todo.v1.LoginResponse
	(*RegisterRequest)(nil),  // 2: todo.todo.v1.RegisterRequest
	(*RegisterResponse)(nil), // 3: todo.todo.v1.RegisterResponse
	(*RefreshRequest)(nil),   // 4: todo.todo.v1.RefreshRequest
	(*RefreshResponse)(nil),  // 5: todo.todo.v1.RefreshResponse
	(*v1.User)(nil),          // 6: todo.common.v1.User
}
var file_todo_todo_v1_auth_proto_depIdxs = []int32{
	6, // 0: todo.todo.v1.LoginResponse.user:type_name -> todo.common.v1.User
	6, // 1: todo.todo.v1.RegisterResponse.user:type_name -> todo.common.v1.User
	0, // 2: todo.todo.v1.AuthService.Login:input_type -> todo.todo.v1.LoginRequest
	2, // 3: todo.todo.v1.AuthService.Register:input_type -> todo.todo.v1.RegisterRequest
	4, // 4: todo.todo.v1.AuthService.Refresh:input_type -> todo.todo.v1.RefreshRequest
	1, // 5: todo.todo.v1.AuthService.Login:output_type -> todo.todo.v1.LoginResponse
	3, // 6: todo.todo.v1.AuthService.Register:output_type -> todo.todo.v1.RegisterResponse
	5, // 7: todo.todo.v1.AuthService.Refresh:output_type -> todo.todo.v1.RefreshResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_todo_todo_v1_auth_proto_init() }
func file_todo_todo_v1_auth_proto_init() {
	if File_todo_todo_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_todo_v1_auth_proto_rawDesc), len(file_todo_todo_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_todo_v1_auth_proto_goTypes,
		DependencyIndexes: file_todo_todo_v1_auth_proto_depIdxs,
		MessageInfos:      file_todo_todo_v1_auth_proto_msgTypes,
	}.Build()
	File_todo_todo_v1_auth_proto = out.File
	file_todo_todo_v1_auth_proto_goTypes = nil
	file_todo_todo_v1_auth_proto_depIdxs = nil
}
