// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: todo/todo/v1/todo.proto

package todo_todo_v1

import (
	v1 "github.com/phamquanandpad/training-project/grpc/go/todo/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAttributes) Reset() {
	*x = UserAttributes{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAttributes) ProtoMessage() {}

func (x *UserAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAttributes.ProtoReflect.Descriptor instead.
func (*UserAttributes) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{0}
}

func (x *UserAttributes) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTodosRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAttributes *UserAttributes        `protobuf:"bytes,1,opt,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	Offset         int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit          int64                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{1}
}

func (x *ListTodosRequest) GetUserAttributes() *UserAttributes {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *ListTodosRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListTodosRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*v1.Todo             `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{2}
}

func (x *ListTodosResponse) GetTodos() []*v1.Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

func (x *ListTodosResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetTodoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAttributes *UserAttributes        `protobuf:"bytes,1,opt,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	TodoId         int64                  `protobuf:"varint,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoRequest) GetUserAttributes() *UserAttributes {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *GetTodoRequest) GetTodoId() int64 {
	if x != nil {
		return x.TodoId
	}
	return 0
}

type GetTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *v1.Todo               `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoResponse) Reset() {
	*x = GetTodoResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoResponse) ProtoMessage() {}

func (x *GetTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoResponse.ProtoReflect.Descriptor instead.
func (*GetTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{4}
}

func (x *GetTodoResponse) GetTodo() *v1.Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type PostTodoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAttributes *UserAttributes        `protobuf:"bytes,1,opt,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	Task           string                 `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Status         v1.TodoStatus          `protobuf:"varint,4,opt,name=status,proto3,enum=todo.common.v1.TodoStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PostTodoRequest) Reset() {
	*x = PostTodoRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTodoRequest) ProtoMessage() {}

func (x *PostTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTodoRequest.ProtoReflect.Descriptor instead.
func (*PostTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{5}
}

func (x *PostTodoRequest) GetUserAttributes() *UserAttributes {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *PostTodoRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *PostTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PostTodoRequest) GetStatus() v1.TodoStatus {
	if x != nil {
		return x.Status
	}
	return v1.TodoStatus(0)
}

type PostTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *v1.Todo               `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostTodoResponse) Reset() {
	*x = PostTodoResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostTodoResponse) ProtoMessage() {}

func (x *PostTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostTodoResponse.ProtoReflect.Descriptor instead.
func (*PostTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{6}
}

func (x *PostTodoResponse) GetTodo() *v1.Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type PutTodoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAttributes *UserAttributes        `protobuf:"bytes,1,opt,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	TodoId         int64                  `protobuf:"varint,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	Task           string                 `protobuf:"bytes,3,opt,name=task,proto3" json:"task,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status         v1.TodoStatus          `protobuf:"varint,5,opt,name=status,proto3,enum=todo.common.v1.TodoStatus" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PutTodoRequest) Reset() {
	*x = PutTodoRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTodoRequest) ProtoMessage() {}

func (x *PutTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTodoRequest.ProtoReflect.Descriptor instead.
func (*PutTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{7}
}

func (x *PutTodoRequest) GetUserAttributes() *UserAttributes {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *PutTodoRequest) GetTodoId() int64 {
	if x != nil {
		return x.TodoId
	}
	return 0
}

func (x *PutTodoRequest) GetTask() string {
	if x != nil {
		return x.Task
	}
	return ""
}

func (x *PutTodoRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PutTodoRequest) GetStatus() v1.TodoStatus {
	if x != nil {
		return x.Status
	}
	return v1.TodoStatus(0)
}

type PutTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todo          *v1.Todo               `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutTodoResponse) Reset() {
	*x = PutTodoResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutTodoResponse) ProtoMessage() {}

func (x *PutTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutTodoResponse.ProtoReflect.Descriptor instead.
func (*PutTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{8}
}

func (x *PutTodoResponse) GetTodo() *v1.Todo {
	if x != nil {
		return x.Todo
	}
	return nil
}

type DeleteTodoRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAttributes *UserAttributes        `protobuf:"bytes,1,opt,name=user_attributes,json=userAttributes,proto3" json:"user_attributes,omitempty"`
	TodoId         int64                  `protobuf:"varint,2,opt,name=todo_id,json=todoId,proto3" json:"todo_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTodoRequest) GetUserAttributes() *UserAttributes {
	if x != nil {
		return x.UserAttributes
	}
	return nil
}

func (x *DeleteTodoRequest) GetTodoId() int64 {
	if x != nil {
		return x.TodoId
	}
	return 0
}

type DeleteTodoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoResponse) Reset() {
	*x = DeleteTodoResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoResponse) ProtoMessage() {}

func (x *DeleteTodoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoResponse.ProtoReflect.Descriptor instead.
func (*DeleteTodoResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{10}
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResponse) Reset() {
	*x = GetUserResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResponse) ProtoMessage() {}

func (x *GetUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResponse.ProtoReflect.Descriptor instead.
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type PostUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserRequest) Reset() {
	*x = PostUserRequest{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserRequest) ProtoMessage() {}

func (x *PostUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserRequest.ProtoReflect.Descriptor instead.
func (*PostUserRequest) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{13}
}

func (x *PostUserRequest) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type PostUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostUserResponse) Reset() {
	*x = PostUserResponse{}
	mi := &file_todo_todo_v1_todo_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostUserResponse) ProtoMessage() {}

func (x *PostUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todo_todo_v1_todo_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostUserResponse.ProtoReflect.Descriptor instead.
func (*PostUserResponse) Descriptor() ([]byte, []int) {
	return file_todo_todo_v1_todo_proto_rawDescGZIP(), []int{14}
}

var File_todo_todo_v1_todo_proto protoreflect.FileDescriptor

const file_todo_todo_v1_todo_proto_rawDesc = "" +
	"\n" +
	"\x17todo/todo/v1/todo.proto\x12\ftodo.todo.v1\x1a\x1ftodo/common/v1/todo_model.proto\")\n" +
	"\x0eUserAttributes\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x87\x01\n" +
	"\x10ListTodosRequest\x12E\n" +
	"\x0fuser_attributes\x18\x01 \x01(\v2\x1c.todo.todo.v1.UserAttributesR\x0euserAttributes\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x03R\x05limit\"U\n" +
	"\x11ListTodosResponse\x12*\n" +
	"\x05todos\x18\x01 \x03(\v2\x14.todo.common.v1.TodoR\x05todos\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"p\n" +
	"\x0eGetTodoRequest\x12E\n" +
	"\x0fuser_attributes\x18\x01 \x01(\v2\x1c.todo.todo.v1.UserAttributesR\x0euserAttributes\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\x03R\x06todoId\";\n" +
	"\x0fGetTodoResponse\x12(\n" +
	"\x04todo\x18\x01 \x01(\v2\x14.todo.common.v1.TodoR\x04todo\"\xc2\x01\n" +
	"\x0fPostTodoRequest\x12E\n" +
	"\x0fuser_attributes\x18\x01 \x01(\v2\x1c.todo.todo.v1.UserAttributesR\x0euserAttributes\x12\x12\n" +
	"\x04task\x18\x02 \x01(\tR\x04task\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1a.todo.common.v1.TodoStatusR\x06status\"<\n" +
	"\x10PostTodoResponse\x12(\n" +
	"\x04todo\x18\x01 \x01(\v2\x14.todo.common.v1.TodoR\x04todo\"\xda\x01\n" +
	"\x0ePutTodoRequest\x12E\n" +
	"\x0fuser_attributes\x18\x01 \x01(\v2\x1c.todo.todo.v1.UserAttributesR\x0euserAttributes\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\x03R\x06todoId\x12\x12\n" +
	"\x04task\x18\x03 \x01(\tR\x04task\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\x06status\x18\x05 \x01(\x0e2\x1a.todo.common.v1.TodoStatusR\x06status\";\n" +
	"\x0fPutTodoResponse\x12(\n" +
	"\x04todo\x18\x01 \x01(\v2\x14.todo.common.v1.TodoR\x04todo\"s\n" +
	"\x11DeleteTodoRequest\x12E\n" +
	"\x0fuser_attributes\x18\x01 \x01(\v2\x1c.todo.todo.v1.UserAttributesR\x0euserAttributes\x12\x17\n" +
	"\atodo_id\x18\x02 \x01(\x03R\x06todoId\"\x14\n" +
	"\x12DeleteTodoResponse\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\";\n" +
	"\x0fGetUserResponse\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.todo.common.v1.UserR\x04user\";\n" +
	"\x0fPostUserRequest\x12(\n" +
	"\x04user\x18\x01 \x01(\v2\x14.todo.common.v1.UserR\x04user\"\x12\n" +
	"\x10PostUserResponse2\xa8\x04\n" +
	"\vTodoService\x12N\n" +
	"\tListTodos\x12\x1e.todo.todo.v1.ListTodosRequest\x1a\x1f.todo.todo.v1.ListTodosResponse\"\x00\x12H\n" +
	"\aGetTodo\x12\x1c.todo.todo.v1.GetTodoRequest\x1a\x1d.todo.todo.v1.GetTodoResponse\"\x00\x12K\n" +
	"\bPostTodo\x12\x1d.todo.todo.v1.PostTodoRequest\x1a\x1e.todo.todo.v1.PostTodoResponse\"\x00\x12H\n" +
	"\aPutTodo\x12\x1c.todo.todo.v1.PutTodoRequest\x1a\x1d.todo.todo.v1.PutTodoResponse\"\x00\x12Q\n" +
	"\n" +
	"DeleteTodo\x12\x1f.todo.todo.v1.DeleteTodoRequest\x1a .todo.todo.v1.DeleteTodoResponse\"\x00\x12H\n" +
	"\aGetUser\x12\x1c.todo.todo.v1.GetUserRequest\x1a\x1d.todo.todo.v1.GetUserResponse\"\x00\x12K\n" +
	"\bPostUser\x12\x1d.todo.todo.v1.PostUserRequest\x1a\x1e.todo.todo.v1.PostUserResponse\"\x00BNZLgithub.com/phamquanandpad/training-project/grpc/go/todo/todo/v1;todo_todo_v1b\x06proto3"

var (
	file_todo_todo_v1_todo_proto_rawDescOnce sync.Once
	file_todo_todo_v1_todo_proto_rawDescData []byte
)

func file_todo_todo_v1_todo_proto_rawDescGZIP() []byte {
	file_todo_todo_v1_todo_proto_rawDescOnce.Do(func() {
		file_todo_todo_v1_todo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todo_todo_v1_todo_proto_rawDesc), len(file_todo_todo_v1_todo_proto_rawDesc)))
	})
	return file_todo_todo_v1_todo_proto_rawDescData
}

var file_todo_todo_v1_todo_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_todo_todo_v1_todo_proto_goTypes = []any{
	(*UserAttributes)(nil),     // 0: todo.todo.v1.UserAttributes
	(*ListTodosRequest)(nil),   // 1: todo.todo.v1.ListTodosRequest
	(*ListTodosResponse)(nil),  // 2: todo.todo.v1.ListTodosResponse
	(*GetTodoRequest)(nil),     // 3: todo.todo.v1.GetTodoRequest
	(*GetTodoResponse)(nil),    // 4: todo.todo.v1.GetTodoResponse
	(*PostTodoRequest)(nil),    // 5: todo.todo.v1.PostTodoRequest
	(*PostTodoResponse)(nil),   // 6: todo.todo.v1.PostTodoResponse
	(*PutTodoRequest)(nil),     // 7: todo.todo.v1.PutTodoRequest
	(*PutTodoResponse)(nil),    // 8: todo.todo.v1.PutTodoResponse
	(*DeleteTodoRequest)(nil),  // 9: todo.todo.v1.DeleteTodoRequest
	(*DeleteTodoResponse)(nil), // 10: todo.todo.v1.DeleteTodoResponse
	(*GetUserRequest)(nil),     // 11: todo.todo.v1.GetUserRequest
	(*GetUserResponse)(nil),    // 12: todo.todo.v1.GetUserResponse
	(*PostUserRequest)(nil),    // 13: todo.todo.v1.PostUserRequest
	(*PostUserResponse)(nil),   // 14: todo.todo.v1.PostUserResponse
	(*v1.Todo)(nil),            // 15: todo.common.v1.Todo
	(v1.TodoStatus)(0),         // 16: todo.common.v1.TodoStatus
	(*v1.User)(nil),            // 17: todo.common.v1.User
}
var file_todo_todo_v1_todo_proto_depIdxs = []int32{
	0,  // 0: todo.todo.v1.ListTodosRequest.user_attributes:type_name -> todo.todo.v1.UserAttributes
	15, // 1: todo.todo.v1.ListTodosResponse.todos:type_name -> todo.common.v1.Todo
	0,  // 2: todo.todo.v1.GetTodoRequest.user_attributes:type_name -> todo.todo.v1.UserAttributes
	15, // 3: todo.todo.v1.GetTodoResponse.todo:type_name -> todo.common.v1.Todo
	0,  // 4: todo.todo.v1.PostTodoRequest.user_attributes:type_name -> todo.todo.v1.UserAttributes
	16, // 5: todo.todo.v1.PostTodoRequest.status:type_name -> todo.common.v1.TodoStatus
	15, // 6: todo.todo.v1.PostTodoResponse.todo:type_name -> todo.common.v1.Todo
	0,  // 7: todo.todo.v1.PutTodoRequest.user_attributes:type_name -> todo.todo.v1.UserAttributes
	16, // 8: todo.todo.v1.PutTodoRequest.status:type_name -> todo.common.v1.TodoStatus
	15, // 9: todo.todo.v1.PutTodoResponse.todo:type_name -> todo.common.v1.Todo
	0,  // 10: todo.todo.v1.DeleteTodoRequest.user_attributes:type_name -> todo.todo.v1.UserAttributes
	17, // 11: todo.todo.v1.GetUserResponse.user:type_name -> todo.common.v1.User
	17, // 12: todo.todo.v1.PostUserRequest.user:type_name -> todo.common.v1.User
	1,  // 13: todo.todo.v1.TodoService.ListTodos:input_type -> todo.todo.v1.ListTodosRequest
	3,  // 14: todo.todo.v1.TodoService.GetTodo:input_type -> todo.todo.v1.GetTodoRequest
	5,  // 15: todo.todo.v1.TodoService.PostTodo:input_type -> todo.todo.v1.PostTodoRequest
	7,  // 16: todo.todo.v1.TodoService.PutTodo:input_type -> todo.todo.v1.PutTodoRequest
	9,  // 17: todo.todo.v1.TodoService.DeleteTodo:input_type -> todo.todo.v1.DeleteTodoRequest
	11, // 18: todo.todo.v1.TodoService.GetUser:input_type -> todo.todo.v1.GetUserRequest
	13, // 19: todo.todo.v1.TodoService.PostUser:input_type -> todo.todo.v1.PostUserRequest
	2,  // 20: todo.todo.v1.TodoService.ListTodos:output_type -> todo.todo.v1.ListTodosResponse
	4,  // 21: todo.todo.v1.TodoService.GetTodo:output_type -> todo.todo.v1.GetTodoResponse
	6,  // 22: todo.todo.v1.TodoService.PostTodo:output_type -> todo.todo.v1.PostTodoResponse
	8,  // 23: todo.todo.v1.TodoService.PutTodo:output_type -> todo.todo.v1.PutTodoResponse
	10, // 24: todo.todo.v1.TodoService.DeleteTodo:output_type -> todo.todo.v1.DeleteTodoResponse
	12, // 25: todo.todo.v1.TodoService.GetUser:output_type -> todo.todo.v1.GetUserResponse
	14, // 26: todo.todo.v1.TodoService.PostUser:output_type -> todo.todo.v1.PostUserResponse
	20, // [20:27] is the sub-list for method output_type
	13, // [13:20] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_todo_todo_v1_todo_proto_init() }
func file_todo_todo_v1_todo_proto_init() {
	if File_todo_todo_v1_todo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todo_todo_v1_todo_proto_rawDesc), len(file_todo_todo_v1_todo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todo_todo_v1_todo_proto_goTypes,
		DependencyIndexes: file_todo_todo_v1_todo_proto_depIdxs,
		MessageInfos:      file_todo_todo_v1_todo_proto_msgTypes,
	}.Build()
	File_todo_todo_v1_todo_proto = out.File
	file_todo_todo_v1_todo_proto_goTypes = nil
	file_todo_todo_v1_todo_proto_depIdxs = nil
}
