// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/gateway/gateway.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/gateway/gateway.go -destination=internal/domain/gateway/mock/gateway.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/phamquanandpad/training-project/go/services/auth/internal/domain/model/auth"
	todo "github.com/phamquanandpad/training-project/go/services/auth/internal/domain/model/todo"
	gomock "go.uber.org/mock/gomock"
)

// MockBinder is a mock of Binder interface.
type MockBinder struct {
	ctrl     *gomock.Controller
	recorder *MockBinderMockRecorder
	isgomock struct{}
}

// MockBinderMockRecorder is the mock recorder for MockBinder.
type MockBinderMockRecorder struct {
	mock *MockBinder
}

// NewMockBinder creates a new mock instance.
func NewMockBinder(ctrl *gomock.Controller) *MockBinder {
	mock := &MockBinder{ctrl: ctrl}
	mock.recorder = &MockBinderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBinder) EXPECT() *MockBinderMockRecorder {
	return m.recorder
}

// Bind mocks base method.
func (m *MockBinder) Bind(arg0 context.Context) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bind", arg0)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Bind indicates an expected call of Bind.
func (mr *MockBinderMockRecorder) Bind(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bind", reflect.TypeOf((*MockBinder)(nil).Bind), arg0)
}

// MockUserQueriesGateway is a mock of UserQueriesGateway interface.
type MockUserQueriesGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserQueriesGatewayMockRecorder
	isgomock struct{}
}

// MockUserQueriesGatewayMockRecorder is the mock recorder for MockUserQueriesGateway.
type MockUserQueriesGatewayMockRecorder struct {
	mock *MockUserQueriesGateway
}

// NewMockUserQueriesGateway creates a new mock instance.
func NewMockUserQueriesGateway(ctrl *gomock.Controller) *MockUserQueriesGateway {
	mock := &MockUserQueriesGateway{ctrl: ctrl}
	mock.recorder = &MockUserQueriesGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserQueriesGateway) EXPECT() *MockUserQueriesGatewayMockRecorder {
	return m.recorder
}

// GetUserByEmail mocks base method.
func (m *MockUserQueriesGateway) GetUserByEmail(ctx context.Context, email string) (*auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByEmail", ctx, email)
	ret0, _ := ret[0].(*auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByEmail indicates an expected call of GetUserByEmail.
func (mr *MockUserQueriesGatewayMockRecorder) GetUserByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByEmail", reflect.TypeOf((*MockUserQueriesGateway)(nil).GetUserByEmail), ctx, email)
}

// GetUserByID mocks base method.
func (m *MockUserQueriesGateway) GetUserByID(ctx context.Context, userID auth.UserID) (*auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, userID)
	ret0, _ := ret[0].(*auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockUserQueriesGatewayMockRecorder) GetUserByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockUserQueriesGateway)(nil).GetUserByID), ctx, userID)
}

// MockUserCommandsGateway is a mock of UserCommandsGateway interface.
type MockUserCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockUserCommandsGatewayMockRecorder is the mock recorder for MockUserCommandsGateway.
type MockUserCommandsGatewayMockRecorder struct {
	mock *MockUserCommandsGateway
}

// NewMockUserCommandsGateway creates a new mock instance.
func NewMockUserCommandsGateway(ctrl *gomock.Controller) *MockUserCommandsGateway {
	mock := &MockUserCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockUserCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCommandsGateway) EXPECT() *MockUserCommandsGatewayMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserCommandsGateway) CreateUser(ctx context.Context, newUser auth.NewUser) (*auth.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, newUser)
	ret0, _ := ret[0].(*auth.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserCommandsGatewayMockRecorder) CreateUser(ctx, newUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserCommandsGateway)(nil).CreateUser), ctx, newUser)
}

// MockJwtGenerateGateway is a mock of JwtGenerateGateway interface.
type MockJwtGenerateGateway struct {
	ctrl     *gomock.Controller
	recorder *MockJwtGenerateGatewayMockRecorder
	isgomock struct{}
}

// MockJwtGenerateGatewayMockRecorder is the mock recorder for MockJwtGenerateGateway.
type MockJwtGenerateGatewayMockRecorder struct {
	mock *MockJwtGenerateGateway
}

// NewMockJwtGenerateGateway creates a new mock instance.
func NewMockJwtGenerateGateway(ctrl *gomock.Controller) *MockJwtGenerateGateway {
	mock := &MockJwtGenerateGateway{ctrl: ctrl}
	mock.recorder = &MockJwtGenerateGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtGenerateGateway) EXPECT() *MockJwtGenerateGatewayMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJwtGenerateGateway) GenerateAccessToken(userID auth.UserID) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJwtGenerateGatewayMockRecorder) GenerateAccessToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJwtGenerateGateway)(nil).GenerateAccessToken), userID)
}

// GenerateRefreshToken mocks base method.
func (m *MockJwtGenerateGateway) GenerateRefreshToken(userID auth.UserID) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRefreshToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRefreshToken indicates an expected call of GenerateRefreshToken.
func (mr *MockJwtGenerateGatewayMockRecorder) GenerateRefreshToken(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRefreshToken", reflect.TypeOf((*MockJwtGenerateGateway)(nil).GenerateRefreshToken), userID)
}

// MockJwtVerifyGateway is a mock of JwtVerifyGateway interface.
type MockJwtVerifyGateway struct {
	ctrl     *gomock.Controller
	recorder *MockJwtVerifyGatewayMockRecorder
	isgomock struct{}
}

// MockJwtVerifyGatewayMockRecorder is the mock recorder for MockJwtVerifyGateway.
type MockJwtVerifyGatewayMockRecorder struct {
	mock *MockJwtVerifyGateway
}

// NewMockJwtVerifyGateway creates a new mock instance.
func NewMockJwtVerifyGateway(ctrl *gomock.Controller) *MockJwtVerifyGateway {
	mock := &MockJwtVerifyGateway{ctrl: ctrl}
	mock.recorder = &MockJwtVerifyGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJwtVerifyGateway) EXPECT() *MockJwtVerifyGatewayMockRecorder {
	return m.recorder
}

// VerifyAccessToken mocks base method.
func (m *MockJwtVerifyGateway) VerifyAccessToken(token string) (auth.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyAccessToken", token)
	ret0, _ := ret[0].(auth.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyAccessToken indicates an expected call of VerifyAccessToken.
func (mr *MockJwtVerifyGatewayMockRecorder) VerifyAccessToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyAccessToken", reflect.TypeOf((*MockJwtVerifyGateway)(nil).VerifyAccessToken), token)
}

// VerifyRefreshToken mocks base method.
func (m *MockJwtVerifyGateway) VerifyRefreshToken(token string) (auth.UserID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyRefreshToken", token)
	ret0, _ := ret[0].(auth.UserID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyRefreshToken indicates an expected call of VerifyRefreshToken.
func (mr *MockJwtVerifyGatewayMockRecorder) VerifyRefreshToken(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyRefreshToken", reflect.TypeOf((*MockJwtVerifyGateway)(nil).VerifyRefreshToken), token)
}

// MockUserServiceCommandsGateway is a mock of UserServiceCommandsGateway interface.
type MockUserServiceCommandsGateway struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceCommandsGatewayMockRecorder
	isgomock struct{}
}

// MockUserServiceCommandsGatewayMockRecorder is the mock recorder for MockUserServiceCommandsGateway.
type MockUserServiceCommandsGatewayMockRecorder struct {
	mock *MockUserServiceCommandsGateway
}

// NewMockUserServiceCommandsGateway creates a new mock instance.
func NewMockUserServiceCommandsGateway(ctrl *gomock.Controller) *MockUserServiceCommandsGateway {
	mock := &MockUserServiceCommandsGateway{ctrl: ctrl}
	mock.recorder = &MockUserServiceCommandsGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceCommandsGateway) EXPECT() *MockUserServiceCommandsGatewayMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockUserServiceCommandsGateway) CreateUser(ctx context.Context, newUser todo.NewUser) (*todo.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, newUser)
	ret0, _ := ret[0].(*todo.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockUserServiceCommandsGatewayMockRecorder) CreateUser(ctx, newUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockUserServiceCommandsGateway)(nil).CreateUser), ctx, newUser)
}
