// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/interfaces.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/interfaces.go -destination=internal/domain/service/mock/interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	todo "github.com/phamquanandpad/training-project/go/services/todo/internal/domain/model/todo"
	gomock "go.uber.org/mock/gomock"
)

// MockTodoHelper is a mock of TodoHelper interface.
type MockTodoHelper struct {
	ctrl     *gomock.Controller
	recorder *MockTodoHelperMockRecorder
	isgomock struct{}
}

// MockTodoHelperMockRecorder is the mock recorder for MockTodoHelper.
type MockTodoHelperMockRecorder struct {
	mock *MockTodoHelper
}

// NewMockTodoHelper creates a new mock instance.
func NewMockTodoHelper(ctrl *gomock.Controller) *MockTodoHelper {
	mock := &MockTodoHelper{ctrl: ctrl}
	mock.recorder = &MockTodoHelperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTodoHelper) EXPECT() *MockTodoHelperMockRecorder {
	return m.recorder
}

// CanAccessTodo mocks base method.
func (m *MockTodoHelper) CanAccessTodo(ctx context.Context, userID todo.UserID, todoID todo.TodoID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanAccessTodo", ctx, userID, todoID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanAccessTodo indicates an expected call of CanAccessTodo.
func (mr *MockTodoHelperMockRecorder) CanAccessTodo(ctx, userID, todoID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanAccessTodo", reflect.TypeOf((*MockTodoHelper)(nil).CanAccessTodo), ctx, userID, todoID)
}
